name: Run Fractal Script

on:
  push:
    paths:
      - 'scripts/script3.py'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy

      - name: Run fractal script
        run: python scripts/script3.py

      - name: Upload fractal image
        uses: actions/upload-artifact@v4
        with:
          name: fractal-image
          path: output/fractal.png
